# fly.toml app configuration file generated for agilemeets-basemgt on 2024-11-04T08:43:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agilemeets-basemgt'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"
  context = "."

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  RABBITMQ__HOSTNAME = "agilemeets-rabbitmq.internal"
  RABBITMQ__USERNAME = "guest"
  RABBITMQ__PASSWORD = "guest"
  RABBITMQ__QUEUES = '{"Notifications":"notifications_queue"}'
  RABBITMQ__VIRTUALHOST = '/'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
