// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0homgQlYO39UwNpUXkg932mv8hCTLfXA',
    appId: '1:1004592372683:web:487e952be5f2cfd1c0b44e',
    messagingSenderId: '1004592372683',
    projectId: 'agilemeets',
    authDomain: 'agilemeets.firebaseapp.com',
    storageBucket: 'agilemeets.firebasestorage.app',
    measurementId: 'G-63ZB9NK9TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4DUBXDncDwL6uXMTiburkejwavZkc6c',
    appId: '1:1004592372683:android:5740bf6cca0f8562c0b44e',
    messagingSenderId: '1004592372683',
    projectId: 'agilemeets',
    storageBucket: 'agilemeets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLE_p-lvLClx1hzHn8xO4thvYr5021hoY',
    appId: '1:1004592372683:ios:6fd1509b5ca8fe12c0b44e',
    messagingSenderId: '1004592372683',
    projectId: 'agilemeets',
    storageBucket: 'agilemeets.firebasestorage.app',
    iosBundleId: 'com.example.agilemeetsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLE_p-lvLClx1hzHn8xO4thvYr5021hoY',
    appId: '1:1004592372683:ios:6fd1509b5ca8fe12c0b44e',
    messagingSenderId: '1004592372683',
    projectId: 'agilemeets',
    storageBucket: 'agilemeets.firebasestorage.app',
    iosBundleId: 'com.example.agilemeetsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0homgQlYO39UwNpUXkg932mv8hCTLfXA',
    appId: '1:1004592372683:web:9cc7aca99751d2f9c0b44e',
    messagingSenderId: '1004592372683',
    projectId: 'agilemeets',
    authDomain: 'agilemeets.firebaseapp.com',
    storageBucket: 'agilemeets.firebasestorage.app',
    measurementId: 'G-14YL9G79FP',
  );
}
