# fly.toml app configuration file generated for agilemeets-notification on 2024-11-04T09:04:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agilemeets-notification'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  context = '.'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  RABBITMQ__HOSTNAME = 'agilemeets-rabbitmq.internal'
  RABBITMQ__PASSWORD = 'guest'
  RABBITMQ__QUEUENAME = "notifications_queue"
  RABBITMQ__USERNAME = 'guest'
  RABBITMQ__VIRTUALHOST = '/'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 8081

  [[services.ports]]
    port = 8081
    handlers = ["http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
