apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  username: agileai_user
  password: RootRoot1.
  connection-string: Host=postgres;Database=Senior_AgileAI_BaseMgt;Username=agileai_user;Password=RootRoot1.;
