# fly.toml app configuration file generated for agilemeets-meeting on 2025-01-25T07:09:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agilemeets-meeting'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEFAULT_APP_ADMIN_PASSWORD = '***REDACTED***'
  DEFAULT_APP_ADMIN_USERNAME = 'calladmin'
  DEFAULT_APP_PASSWORD = '***REDACTED***'
  DEFAULT_APP_USERNAME = 'calluser'
  DOMAIN_NAME = 'meeting.agilemeets.com'
  ENABLED_MODULES = 'observability,app'
  LETSENCRYPT_EMAIL = 'agilemeets.noreply@gmail.com'
  LIVEKIT_API_KEY = '***REDACTED***'
  LIVEKIT_API_SECRET = '***REDACTED***'
  LIVEKIT_TURN_DOMAIN_NAME = 'none'
  LIVEKIT_URL = 'wss://meeting.agilemeets.com'
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '8082'
  RABBITMQ__HOSTNAME = 'agilemeets-rabbitmq.internal'
  RABBITMQ__PASSWORD = '***REDACTED***'
  RABBITMQ__USERNAME = 'guest'
  RABBITMQ__VIRTUALHOST = '/'
  AWS_ACCESS_KEY = '***REDACTED***'
  AWS_SECRET_KEY = '***REDACTED***'
  AWS_BUCKET_NAME = 'agilemeets-meetings'

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 8082

  [[services.ports]]
    port = 8082
    handlers = ['http']


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
