version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: Senior_AgileAI_BaseMgt
      POSTGRES_USER: agileai_user
      POSTGRES_PASSWORD: RootRoot1.
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agileai_user -d Senior_AgileAI_BaseMgt"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    build:
      context: ..
      dockerfile: Docker/RabbitMQ.Dockerfile  # <-- point to your new Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  basemgt_api:
    build:
      context: ..
      dockerfile: Docker/BaseMgt.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSqlConnection=Host=db;Database=Senior_AgileAI_BaseMgt;Username=agileai_user;Password=RootRoot1.;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Queues__Notifications=notifications_queue
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification_service:
    build:
      context: ..
      dockerfile: Docker/NotificationService.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=notifications_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:
